[phases.setup]
nixpkgs = ["https://nixos.org/nixpkgs/archive/nixos-23.05.tar.gz"]

[phases.build]
nixpkgs = "https://nixos.org/nixpkgs/archive/nixos-23.05.tar.gz"
cmd = "npm install && npm run build"

[start]
nixpkgs = "https://nixos.org/nixpkgs/archive/nixos-23.05.tar.gz"
cmd = "npm install && npm run start"
